version: '3.3'
services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/prometheus-data/prometheus.yml
    command:
      - "--config.file=/prometheus-data/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
  
  grafana:
    image: grafana/grafana
    ports: 
      - 3000:3000
    volumes: 
      - ./config/grafana:/grafana-provisioning
    depends_on: 
      - prometheus
    environment: 
      GF_PATHS_PROVISIONING: /grafana-provisioning
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    user: "1000"